name:         haskell-string-conversions
version:      0.0.1.0
synopsis:     haskell-string-conversions
author:       haskell-string-conversions
github:       haskell-string-conversions/haskell-string-conversions
category:     haskell-string-conversions

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

_exe-ghc-options:        &exe-ghc-options
- -threaded
- -rtsopts
- -with-rtsopts=-N

tests:
  test:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:         *exe-ghc-options
    dependencies:
      - base >=4.11 && < 5
      - bytestring
      - hspec
      - relude
      - text
      - utf8-string
